stages:
- name: Build
  steps:
  - runScriptConfig:
      image: php:latest
      shellScript: |-
        composer config repo.packagist composer https://packagist.laravel-china.org
        composer update
- name: Push
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: test/k3y
      registry: harbor.woldy.net:8001
timeout: 60
notification: {}
