stages:
- name: Build
  steps:
  - runScriptConfig:
      image: composer
      shellScript: |-
        #composer config repo.packagist composer https://packagist.laravel-china.org
        #composer update
- name: Push
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: test/k3y
      pushRemote: true
      registry: harbor.woldy.net:8001
timeout: 60
notification: {}
