stages:
- name: Build
  steps:
  - runScriptConfig:
      image: composer
      shellScript: composer update
- name: Push
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: test/k3y
      pushRemote: true
      registry: harbor.zhiyinlou.com
timeout: 60
