apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: k3y
  namespace: env-test
  labels:
        app:k3y
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: k3y
        image: harbor.zhiyinlou.com/test/k3y:latest
#        command: [ "/bin/bash", "-c", "--" ]
#        args: [ "while true; do sleep 30; done;" ]
        imagePullPolicy: Always
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: {}
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
